name: Python

on:
  push:
    branches: [ "master" ]
    paths:
      - "src/app/**"
      - "**/**/py**"
      - "poetry**"
      - ".flake8"
  pull_request:
    branches: [ "master" ]
    paths:
      - "src/app/**"
      - "py*"
      - "poetry*"
      - ".flake8"
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        # see details (matrix, python-version, python-version-file, etc.)
        # https://github.com/actions/setup-python
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
      - name: Setup a local virtual environment
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - uses: actions/cache@v3
        name: Setup Virtual Environment
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install Dependencies
        run: poetry install
      - name: Test
        run: poetry run poe test
      - name: Lint
        run: poetry run poe lint