name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
    paths:
      - "src/client/**"
      - "*.js"
      - "*package*.json"
  pull_request:
    branches: [ "master" ]
    paths: 
      - "src/client/**"
      - "*.js"
      - "*package*.json"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['latest', 21.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm install
    - name: Lint Client
      run: npm run lint